[project]
name = "python datascience"
version = "42"
dependencies = ["pandas","numpy","matplotlib","azure-cosmos","azure-kusto-data","azure-kusto-ingest"]

[project.optional-dependencies]
dev = ["ipykernel"]
